[INFO] Module GCC/9.4.0 loaded.

Inactive Modules:
  1) UCX/1.17.0     2) numactl/2.0.16

The following have been reloaded with a version change:
  1) GCCcore/.11.3.0 => GCCcore/.9.4.0     3) zlib/1.2.13 => zlib/1.2.11
  2) binutils/2.38 => binutils/2.36.1

[INFO] Module CUDA/11.8.0 loaded.
[INFO] Module cuDNN/8.6.0.163-CUDA-11.8.0 loaded.
Traceback (most recent call last):
  File "/home/md334167/elzerman-with-unet/aenc_train.py", line 156, in <module>
    main()
  File "/home/md334167/elzerman-with-unet/aenc_train.py", line 145, in main
    train_loader, val_loader = get_loaders(s)
                               ^^^^^^^^^^^^^^
  File "/home/md334167/elzerman-with-unet/aenc_train.py", line 66, in get_loaders
    train_scaler.fit_from_hdf5(hdf5_file_path)
  File "/rwthfs/rz/cluster/home/md334167/elzerman-with-unet/dataset.py", line 195, in fit_from_hdf5
    with h5py.File(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/md334167/miniconda3/envs/DL/lib/python3.11/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (bad object header version number)
/var/spool/slurm/job47908453/slurm_script: line 34: 130722 Bus error               (core dumped) python -u /home/md334167/elzerman-with-unet/aenc_train.py
